# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postcomment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
