# Generated by Django 4.0.6 on 2022-08-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-created',)},
        ),
    ]
