# Generated by Django 4.0.6 on 2022-08-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
